Inventory/urls.py
from django.contrib import admin
from django.urls import path
from main_app import views
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from main_app import views

app_name = 'main_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('user/', views.userPage, name='userPage'),
    path('settings/', views.accountSettings, name='accountSettings'),
    
    path('user_purchase/', views.customerPurchase, name='userPurchase'),
    path('user/purchase_details/<str:pk>/', views.purchaseDetails, name='purchaseDetails'),

    path('purchase/', views.purchase, name='purchase'), # This form should be shown in dashboard
    path('sales/', views.sales, name='sales'), # This form should be shown in dashboard

    path('itemforms/', views.itemForm, name='itemForms'),
    path('updateItem/<str:pk>/', views.updateItem, name='updateItem'),
    path('deleteItem/<str:pk>/', views.deleteItem, name='deleteItem'),

    path('categoryforms/', views.createCategory, name='createCategory'),
    path('updateCategory/<str:pk>/', views.updateCategory, name='updateCategory'),
    path('deleteCategory/<str:pk>/', views.deleteCategory, name='deleteCategory'),

    path('subcategoryforms/', views.createSubCategory, name='createSubCategory'),
    path('updateSubCategory/<str:pk>/', views.updateSubCategory, name='updateSubCategory'),
    path('deleteSubCategory/<str:pk>/', views.deleteSubCategory, name='deleteSubCategory'),

    path('brandforms/', views.createBrand, name='createBrand'),
    path('updateBrand/<str:pk>/', views.updateBrand, name='updateBrand'),
    path('deleteBrand/<str:pk>/', views.deleteBrand, name='deleteBrand'),

    path('supplierforms/', views.createSupplier, name='createSupplier'),
    path('updateSupplier/<str:pk>/', views.updateSupplier, name='updateSupplier'),
    path('deleteSupplier/<str:pk>/', views.deleteSupplier, name='deleteSupplier'),

    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutUser, name='logout'),

    path('test/', views.test, name='test'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Supplier(models.Model):
    name = models.CharField(max_length=50)
    contact = models.CharField(max_length=10)
    email = models.EmailField()
    address = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=12, null=True, blank=True)
    profile_pic = models.ImageField(default='profile1.png', blank=True, null=True)

    def __str__(self):
        return str(self.user.username)

class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class SubCategory(models.Model):
    cat = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True, blank=True)
    cat = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    subCat = models.ForeignKey(SubCategory, on_delete=models.CASCADE, null=True, blank=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE,  null=True, blank=True) # This is not solved
    quantity = models.DecimalField(default=0, max_digits=5, decimal_places=0)
    available = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return self.name

class Sales(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=5, decimal_places=0)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date = models.DateTimeField()
    
    def __str__(self):
        return str(self.item.name)

class Purchase(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=5, decimal_places=0)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    date = models.DateTimeField()

    def __str__(self):
        return str(self.item.name)

main_app/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

class PurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = '__all__'

class SalesForm(forms.ModelForm):
    class Meta:
        model = Sales
        fields = '__all__'

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']

class categoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class subCategoryForm(forms.ModelForm):
    class Meta:
        model = SubCategory
        fields = '__all__'

class brandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = '__all__'

class supplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = '__all__'

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item, Customer
from .forms import *
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import *
from django.contrib.auth.models import Group
from django.http import JsonResponse
from django.forms.models import model_to_dict
#Create your views here.

# Admin Pages
@login_required(login_url='main_app:login')
@admin_only
def index(request):
    my_dict = {}
    return render(request, 'main_app/index.html', context=my_dict)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def dashboard(request):
    item = Item.objects.all()
    category = Category.objects.all()
    subcategory = SubCategory.objects.all()
    brand = Brand.objects.all()
    supplier = Supplier.objects.all()
    data_dict = {
        'item_table': item,
        'category_table': category,
        'subCategory_table': subcategory,
        'brand_table': brand,
        'supplier_table': supplier,
    }
    return render(request, 'main_app/dashboard.html', context=data_dict)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def itemForm(request):
    form = ItemForm()
    if request.method == 'POST':
        form = ItemForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('main_app:dashboard')

        else:
            print("Error form invalid")

            
    return render(request, 'main_app/forms.html',{'form': form})

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def updateItem(request, pk):
    item = Item.objects.get(id=pk)
    form = ItemForm(instance=item)
    if request.method == "POST":
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('main_app:dashboard')
    
    return render(request, 'main_app/forms.html', {'form':form})

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def deleteItem(request, pk):
    item = Item.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('main_app:dashboard')
    context = {'item': item, 'tableName': 'deleteItem'}
    return render(request, 'main_app/deleteItem.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def purchase(request):
    form = PurchaseForm()
    if request.method == 'POST':
        form = PurchaseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main_app:dashboard')

    context = {'form': form}
    return render(request, 'main_app/forms.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def sales(request):
    form = SalesForm()
    if request.method == 'POST':
        form = SalesForm(request.POST)
        if form.is_valid():
            item = form.cleaned_data.get('item')
            qty = form.cleaned_data.get('quantity')
            print(item)
            if qty <= item.quantity:
                sales = form.save()
                return redirect('main_app:dashboard')

            else:
                messages.info(request, "Not enough item")

    context = {'form': form}
    return render(request, 'main_app/forms.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def createCategory(request):
    form = categoryForm()
    if request.method == 'POST':
        form = categoryForm(request.POST)
        if form.is_valid():
            form.save()

    context = {'form': form}
    return render(request, 'main_app/forms.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def updateCategory(request, pk):
    item = Category.objects.get(id=pk)
    form = categoryForm(instance=item)
    if request.method == "POST":
        form = categoryForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('main_app:dashboard')
    
    return render(request, 'main_app/forms.html', {'form':form})

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def deleteCategory(request, pk):
    item = Category.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('main_app:dashboard')
    context = {'item': item, 'tableName': 'deleteItem'}
    return render(request, 'main_app/deleteItem.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def createSubCategory(request):
    form = subCategoryForm()
    if request.method == 'POST':
        form = subCategoryForm(request.POST)
        if form.is_valid():
            form.save()

    context = {'form': form}
    return render(request, 'main_app/forms.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def updateSubCategory(request, pk):
    item = SubCategory.objects.get(id=pk)
    form = subCategoryForm(instance=item)
    if request.method == "POST":
        form = subCategoryForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('main_app:dashboard')
    
    return render(request, 'main_app/forms.html', {'form':form})

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def deleteSubCategory(request, pk):
    item = SubCategory.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('main_app:dashboard')
    context = {'item': item, 'tableName': 'deleteItem'}
    return render(request, 'main_app/deleteItem.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def createSupplier(request):
    form = supplierForm()
    if request.method == 'POST':
        form = supplierForm(request.POST)
        if form.is_valid():
            form.save()

    context = {'form': form}
    return render(request, 'main_app/forms.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def updateSupplier(request, pk):
    item = Supplier.objects.get(id=pk)
    form = supplierForm(instance=item)
    if request.method == "POST":
        form = supplierForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('main_app:dashboard')
    
    return render(request, 'main_app/forms.html', {'form':form})

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def deleteSupplier(request, pk):
    item = Supplier.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('main_app:dashboard')
    context = {'item': item, 'tableName': 'deleteItem'}
    return render(request, 'main_app/deleteItem.html', context)


@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def createBrand(request):
    form = brandForm()
    if request.method == 'POST':
        form = brandForm(request.POST)
        if form.is_valid():
            form.save()

    context = {'form': form}
    return render(request, 'main_app/forms.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def updateBrand(request, pk):
    item = Brand.objects.get(id=pk)
    form = brandForm(instance=item)
    if request.method == "POST":
        form = brandForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('main_app:dashboard')
    
    return render(request, 'main_app/forms.html', {'form':form})

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Admin'])
def deleteBrand(request, pk):
    item = Brand.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('main_app:dashboard')
    context = {'item': item, 'tableName': 'deleteItem'}
    return render(request, 'main_app/deleteItem.html', context)

# Login and Register Pages
@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main_app:index')
        else:
            messages.info(request, 'Username or Password is incorrect')

    context = {}
    return render(request, 'main_app/login.html', context)

@unauthenticated_user
def registerPage(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Accounts was created for ' + username)
            return redirect('main_app:login')
        
    context = {'form': form}
    return render(request, 'main_app/register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('main_app:login')


# User Pages
@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Customer'])
def userPage(request):
    purchase = request.user.customer.sales_set.all()
    context = {'purchase': purchase}
    return render(request, 'main_app/customer.html', context)

@login_required(login_url='main_app:login')
@allowed_user(allowed_roles=['Customer'])
def accountSettings(request):
    user = request.user.customer
    form = CustomerForm(instance=user)
    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()

templates/main_app/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>

    <title>Inventory</title>
  </head>
  <body>

    <div class="wrapper">
      <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
          <a class="navbar-brand" href="#">Hello, {{ request.user }}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav">
              {% if request.user.is_staff %}
              <li class="nav-item active">
                  <a class="nav-link active" href="{% url 'main_app:index' %}">Home</a> 
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'main_app:dashboard' %}">Dashboard</a>
              </li>
              {% else %}
              <li class="nav-item">
                  <a class="nav-link active" href="{% url 'main_app:accountSettings' %}">Settings</a>
              </li>
              {% endif %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'main_app:logout' %}">Logout</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </div>

    <div class="wrapper">
      <div class="container">
        {% block body_block %}
          
        {% endblock body_block %}
      </div>
    </div>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->

    {% block scriptspace %}
        
    {% endblock scriptspace %}
  </body>
</html>

templates/main_app/customer.html
{% extends 'main_app/base.html' %}

{% load static %}
{% block body_block %}
    <div class="row justify-content-center px-5 py-5">
        <div class="col-2">
            <a class="btn btn-success" href="{% url 'main_app:userPurchase' %}">Make Purchase</a>
        </div>
    </div>
    <div class="row justify-content-center gx-5 gy-5">
        <div class="col-6">
            <table id="purchaseList" class="table table-hover">
                <tr>
                    <th>Item</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Date</th>
                    <th>Details</th>
                </tr>
                
                {% for item in purchase %}
                    <tr">
                        <td>{{ item.item.name }}</td>
                        <td>{{ item.item.price }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.date }}</td>
                        <!-- <td><a href="{% url 'main_app:purchaseDetails' item.id %}">Details</a></td> -->
                        <td><button type="button" class='btn btn-info' data-id="{{ item.id }}" >Details</button></td>
                    </tr>
                {% endfor %}

            </table>

            <div class="details">

            </div>
        </div>
    </div>
{% endblock body_block %}


{% block scriptspace %}
    <script src="{% static 'js/customer.js' %}"></script>
{% endblock scriptspace %}
    
    

templates/main_app/dashboard.html
<!DOCTYPE html>
{% extends 'main_app/base.html' %}

{% block body_block %}
<div class="row">
    <div class="col-2 px-2 py-3 px-2">
        <div class="position-sticky shadow">
            <div class="list-group list-group-flush" id="list-tab" role="tablist">
                <a class="list-group-item list-group-item-action active" id="list-home-list" data-bs-toggle="list" href="#list-item" role="tab" aria-controls="item">Items</a>
                <a class="list-group-item list-group-item-action" id="list-home-list" data-bs-toggle="list" href="#list-category" role="tab" aria-controls="category">Category</a>
                <a class="list-group-item list-group-item-action" id="list-home-list" data-bs-toggle="list" href="#list-sub-category" role="tab" aria-controls="sub-category">Sub-Category</a>
                <a class="list-group-item list-group-item-action" id="list-home-list" data-bs-toggle="list" href="#list-brand" role="tab" aria-controls="brand">Brand</a>
                <a class="list-group-item list-group-item-action" id="list-home-list" data-bs-toggle="list" href="#list-supplier" role="tab" aria-controls="supplier">Supplier</a>
                <a class="list-group-item list-group-item-action" id="list-home-list" href="{% url 'main_app:purchase' %}" role="tab" aria-controls="purchase">Make Purchase</a>
                <a class="list-group-item list-group-item-action" id="list-profile-list" href="{% url 'main_app:sales' %}" role="tab" aria-controls="sales">Make Sales</a>
            </div>
        </div>
    </div>
    <div class="col-10 px-2 py-3 px-2">
        <div class="row justify-content-center shadow">
            <div class="col">
                <h1>Cards</h1>
            </div>
        </div>
        <div class="row justify-content-center shadow py-5">
            <div class="col-10">
                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="list-item" role="tabpanel" aria-labelledby="list-home-list">
                        <div class="tables py-3">
                            <h2>Items table</h2>
                            <div>
                                <a class="btn btn-success" href="{% url 'main_app:itemForms' %}">Create Item</a>
                            </div>
                            {% if item_table %}
                            <table class="table table-hover">
                                <thead>
                                    <th>Item</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Brand</th>
                                    <th>Category</th>
                                    <th>Sub Category</th>
                                    <th>Availability</th>
                                    <th>Action</th>
                                </thead>
                            
                            
                                {% for item in item_table %}
                            
                                <tr>
                                    <td>{{ item.name }}</td>
                                    <td>{{ item.price }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>{{ item.brand }}</td>
                                    <td>{{ item.cat }}</td>
                                    <td>{{ item.subCat }}</td>
                                    <td>{{ item.available }}</td>
                                    <td>
                                        <a class="btn btn-info" href="{% url 'main_app:updateItem' item.id %}">Update</a>
                                        <a class="btn btn-danger" href="{% url 'main_app:deleteItem' item.id %}">Remove</a>
                                    </td>
                                </tr>
                            
                                {% endfor %}
                            
                            
                            </table>
                            {% endif %}
                        </div>
                    </div>
                    <div class="tab-pane fade" id="list-category" role="tabpanel" aria-labelledby="list-profile-list">
                        <div class="table py-3">
                            <h2>Category table</h2>
                            <a class="btn btn-success" href="{% url 'main_app:createCategory' %}">Create Category</a>
                            {% if category_table %}
                            <table class="table table-hover">
                                <thead>
                                    <th>SN</th>
                                    <th>Category</th>
                                    <th>Action</th>
                                </thead>
                                {% for item in category_table %}
                                <tr>
                                    <td>{{ item.id }}</td>
                                    <td>{{ item.name }}</td>
                                    <td>
                                        <a class="btn btn-info" href="{% url 'main_app:updateCategory' item.id %}">Update</a>
                                        <a class="btn btn-danger" href="{% url 'main_app:deleteCategory' item.id %}">Remove</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </table>
                            {% endif %}
                        </div>
                    </div>
                    <div class="tab-pane fade" id="list-sub-category" role="tabpanel" aria-labelledby="list-messages-list">
                        <div class="table py-3">
                            <h2>SubCategor table</h2>
                            <a class="btn btn-success" href="{% url 'main_app:createSubCategory' %}">Create SubCategory</a>
                            {% if subCategory_table %}
                            <table class="table table-hover">
                                <thead>
                                    <th>SN</th>
                                    <th>Category</th>
                                    <th>Sub Category</th>
                                    <th>Action</th>
                                </thead>
                                {% for item in subCategory_table %}
                                <tr>
                                    <td>{{ item.id }}</td>
                                    <td>{{ item.cat.name }}</td>
                                    <td>{{ item.name }}</td>
                                    <td>
                                        <a class="btn btn-info" href="{% url 'main_app:updateSubCategory' item.id %}">Update</a>
                                        <a class="btn btn-danger" href="{% url 'main_app:deleteSubCategory' item.id %}">Remove</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </table>
                            {% endif %}
                        </div>
                    </div>
                    <div class="tab-pane fade" id="list-brand" role="tabpanel" aria-labelledby="list-settings-list">
                        <div class="table">
                            <h2>Brand table</h2>
                            <a class="btn btn-success" href="{% url 'main_app:createBrand' %}">Create Brand</a>
                            {% if brand_table %}
                            <table class="table table-hover">
                                <thead>
                                    <th>SN</th>
                                    <th>Brand</th>
                                    <th>Action</th>
                                </thead>
                                {% for item in brand_table %}
                                <tr>
                                    <td>{{ item.id }}</td>
                                    <td>{{ item.name }}</td>
                                    <td>
                                        <a class="btn btn-info" href="{% url 'main_app:updateBrand' item.id %}">Update</a>
                                        <a class="btn btn-danger" href="{% url 'main_app:deleteBrand' item.id %}">Remove</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </table>
                            {% endif %}
                        </div>
                    </div>
                    <div class="tab-pane fade" id="list-supplier" role="tabpanel" aria-labelledby="list-settings-list">
                        <div class="table">
                            <h2>Supplier table</h2>
                            <a class="btn btn-success" href="{% url 'main_app:createSupplier' %}">Create Supplier</a>
                            {% if supplier_table %}
                            <table class="table table-hover">
                                <thead>
                                    <th>SN</th>
                                    <th>Name</th>
                                    <th>Contact</th>
                                    <th>Email</th>
                                    <th>Address</th>
                                    <th>Action</th>
                                </thead>
                                {% for item in supplier_table %}
                                <tr>
                                    <td>{{ item.id }}</td>
                                    <td>{{ item.name }}</td>
                                    <td>{{ item.contact }}</td>
                                    <td>{{ item.email }}</td>
                                    <td>{{ item.address }}</td>
                                    <td>
                                        <a class="btn btn-info" href="{% url 'main_app:updateSupplier' item.id %}">Update</a>
                                        <a class="btn btn-danger" href="{% url 'main_app:deleteSupplier' item.id %}">Remove</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </table>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body_block %}
    

templates/main_app/deleteItem.html
<!DOCTYPE html>
{% extends 'main_app/base.html' %}

{% block body_block %}
<div class="row justify-content-center">
    <div class="col-4">
        <p>Are you sure you want to delete "{{ item }}"</p>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-3">
        <form method="POST">
            {% csrf_token %}
            <a class="btn btn-warning" href="{% url 'main_app:dashboard' %}">Cancle</a>
            <input class="btn btn-danger" type="submit" name="Confirm">
        </form>
    </div>
</div>
{% endblock body_block %}